#!/usr/bin/env python3
"""regenerate the derived metadata files from the html pages that actually deploy.

generates:  sitemap.xml, robots.txt, llms.txt, openapi.json
run it yourself:  python3 scripts/gen-meta.py
DON'T hand-edit any of those four files - they get clobbered every push.
"""
import json
import os
import re

BASE = "https://izam-mohammed.github.io"
DEPLOYINCLUDE = ".deployinclude"

TITLE_RE = re.compile(r"<title>(.*?)</title>", re.S)
DESC_RE = re.compile(r'<meta\s+name="description"\s+content="(.*?)"', re.S)


def collect_pages():
    """every deployable index.html, as (url_path, file_path). root first, then alpha."""
    with open(DEPLOYINCLUDE) as f:
        include = [line.strip() for line in f if line.strip()]
    dirs = [i for i in include if os.path.isdir(i)]

    pages = []
    if "index.html" in include and os.path.isfile("index.html"):
        pages.append(("", "index.html"))
    for d in dirs:
        for root, _, files in os.walk(d):
            if "index.html" in files:
                rel = os.path.relpath(root, ".").replace(os.sep, "/")
                pages.append((rel + "/", os.path.join(root, "index.html")))

    seen, out = set(), []
    for url, path in sorted(pages, key=lambda p: (p[0] != "", p[0])):
        if url not in seen:
            seen.add(url)
            out.append((url, path))
    return out


def meta(file_path):
    html = open(file_path, encoding="utf-8").read()
    title = TITLE_RE.search(html)
    desc = DESC_RE.search(html)
    title = title.group(1).strip() if title else ""
    desc = desc.group(1).strip() if desc else ""
    # drop the " - Izam Mohammed" suffix for a cleaner name
    name = title.rsplit(" - Izam Mohammed", 1)[0].strip() or title
    return name, desc


def priority(url):
    if url == "":
        return "1.0"
    if url == "brain-dumps/":
        return "0.8"
    return "0.6"


def write_sitemap(pages):
    out = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
        "    <!-- auto-generated by scripts/gen-meta.py - do NOT hand-edit -->",
    ]
    for url, _ in pages:
        out += [
            "    <url>",
            f"        <loc>{BASE}/{url}</loc>",
            f"        <priority>{priority(url)}</priority>",
            "        <changefreq>monthly</changefreq>",
            "    </url>",
        ]
    out.append("</urlset>")
    open("sitemap.xml", "w").write("\n".join(out) + "\n")


def write_robots():
    out = [
        "# yo robots, welcome to the simplest website on the internet",
        "# crawl whatever you want, there's nothin' to hide here",
        "# (except the email, good luck decryptin' that rot13)",
        "# this file is auto-generated by scripts/gen-meta.py",
        "",
        "User-agent: *",
        "Allow: /",
        "",
        "# the sitemap, if you're into that kinda thing",
        f"Sitemap: {BASE}/sitemap.xml",
        "",
        "# dear ai scrapers: there's an llms.txt for you, go read that instead",
        f"# {BASE}/llms.txt",
        "# also this site loads in 0.001 seconds, please don't make it slower. thanks",
    ]
    open("robots.txt", "w").write("\n".join(out) + "\n")


def write_llms(pages):
    home_desc = next((meta(p)[1] for url, p in pages if url == ""), "")
    out = [
        "# Izam Mohammed",
        "",
        f"> {home_desc}",
        "",
        "this is his personal site - a pile of brain dumps. plain html, no frameworks, "
        "loads instantly. below is every page with a one-line summary.",
        "",
        "## Main",
        "",
    ]
    rest = []
    for url, path in pages:
        name, desc = meta(path)
        if url == "":
            name = "home"
        line = f"- [{name}]({BASE}/{url}): {desc}"
        (out if url in ("", "brain-dumps/") else rest).append(line)
    out += ["", "## Brain dumps", ""] + rest
    open("llms.txt", "w").write("\n".join(out) + "\n")


def write_openapi(pages):
    paths = {}
    for url, path in pages:
        name, desc = meta(path)
        route = "/" + url
        op_id = (url.strip("/").replace("/", "_") or "home")
        paths[route] = {
            "get": {
                "operationId": f"get_{op_id}",
                "summary": name or "home",
                "description": desc,
                "responses": {
                    "200": {
                        "description": "the page, served as html",
                        "content": {"text/html": {}},
                    }
                },
            }
        }
    spec = {
        "openapi": "3.1.0",
        "info": {
            "title": "izam-mohammed.github.io",
            "version": "1.0.0",
            "description": (
                "there's no real api here - it's a static site. but if you squint, every "
                "page is a GET endpoint that returns html. so here's that, documented. "
                "auto-generated by scripts/gen-meta.py, don't @ me."
            ),
        },
        "servers": [{"url": BASE}],
        "paths": paths,
    }
    open("openapi.json", "w").write(json.dumps(spec, indent=2) + "\n")


if __name__ == "__main__":
    pages = collect_pages()
    write_sitemap(pages)
    write_robots()
    write_llms(pages)
    write_openapi(pages)
    print(f"regenerated sitemap.xml, robots.txt, llms.txt, openapi.json from {len(pages)} pages")
